export const SPORTS_SYNC_PROVIDER_BUDGET_MS = 30_000;
export const SPORTS_SYNC_PG_NET_TIMEOUT_MS = 45_000;
export const SPORTS_SYNC_ROUTE_MAX_DURATION_SECONDS = 60;
export const SPORTS_SYNC_LEASE_DURATION_MS = 120_000;
